### PR TITLE
docker-compose up fails Issue#233

### PR DESCRIPTION
**Pull request by cduranleau**
Recreates the pip requirements.txt structure before running pip install.

### CODE REVIEW

**Comment by cduranleau** [comment]
Successful 'docker-compose up -d' command. Might need travis changes. Will look into that next. 

1. https://gist.github.com/cduranleau/e590cf1e94dc6520cab8387ccc49b964

**Comment by april** [comment]
I think we had specifically split these requirements apart in the first place because there were some installations that only wanted a little bit of them (as in the top one). Why can't the pip command install from the top level directory, or use multiple `-r` statements?

**Comment by cduranleau** [comment]
> Why can't the pip command install from the top level directory, or use multiple -r statements?


So that's kinda what I was trying to do, with the bad assumption about no restrictions on splitting the requirements. That said adding multiple -r flags seems like a perfectly reasonable solution as well. And it is a smaller change? I can commit that if you would like. Tested it out locally and it seems to work as well. 


1. https://github.com/mozilla/http-observatory/blob/master/docker-compose.yml#L21
2. https://github.com/mozilla/http-observatory/blob/master/docker-compose.yml#L4

**Comment by cduranleau** [comment]
This is the diff with -r flags instead of dependency chaining. 

{code}M1711995:http-observatory cd033922$ git diff origin/master 
diff --git a/.gitignore b/.gitignore
index 2598fbb..e2c1201 100644
--- a/.gitignore
+++ b/.gitignore
@@ -6,3 +6,4 @@
 __pycache__
 *.py[oc]
 /venv
+.DS_Store
diff --git a/httpobs/Dockerfile b/httpobs/Dockerfile
index 22cb570..1b9e761 100644
--- a/httpobs/Dockerfile
+++ b/httpobs/Dockerfile
@@ -9,11 +9,14 @@ RUN install -o app -g app -d /var/run/httpobs /var/log/httpobs
 
 WORKDIR /app
 
-COPY requirements.txt /app
+COPY . httpobs
 
-RUN pip install --upgrade --no-cache-dir -r requirements.txt
+RUN pip install --upgrade --no-cache-dir \
+    -r httpobs/requirements.txt \
+    -r httpobs/database/requirements.txt \
+    -r httpobs/scanner/requirements.txt \
+    -r httpobs/website/requirements.txt
 
-COPY . httpobs
 ENV PYTHONPATH $PYTHONPATH:/app
 
-USER app
\ No newline at end of file
+USER app
{code}

**Comment by april** [comment]
Sorry about not merging this earlier; I've been out of town for about 80% of the last two weeks. Looks good to me, thanks!

**Comment by cduranleau** [comment]
This may not be the change that was intended. I hadn't pushed the diff in https://github.com/mozilla/http-observatory/pull/243#issuecomment-313196419 yet. I didn't know which ones you wanted. I can get another PR out ASAP or push to this one, whichever is needed.

**Comment by april** [comment]
Ahh yes, if you could send me another PR that would be great.  :)

**Comment by cduranleau** [comment]
Done: https://github.com/mozilla/http-observatory/pull/248

**Pull request merged**
