### PR TITLE
Add support for SameSite cookies

### PR DESCRIPTION
**Pull request by april**
This addresses #64, helping to mitigate the risks from Spectre.

### CODE REVIEW

**Comment by rugk** [comment]
Wait, what do SameSite cookies have to do with Spectre?

**Comment by april** [comment]
The use of X-Content-Type-Options and SameSite cookies can prevent cookies from entering memory. Currently those protections are important for users of Chrome's Site Isolation feature.

**Comment by rugk** [comment]
Ah, so what about Firefox? Does cookies (do not) enter the memory there, too?

Also very interesting correlation generally… is there a blog post for that or do you plan to write one? I'd say that could be worth a blog post. 😄

**Comment by april** [comment]
I'm not sure exactly where Firefox is currently, although I imagine this sort of work will be looked at:
https://www.chromium.org/Home/chromium-security/ssca

**Pull request merged**
