### PR TITLE
Extract HTML content from test_content.py into files/test_*.html.

### PR DESCRIPTION
**Pull request by floatingatoll**
This will fail tests immediately, as for unknown reasons the `empty_resources()` function does not seem to be producing the result @april expected. I don't quite know where to begin diagnosing this, so submitting the PR for assistance since this refactor is now blocking #327.

### CODE REVIEW

**Comment by floatingatoll** [comment]
The tests no longer fail. It turns out that `empty_resources()` was only used previously to load and test HTML `<meta>` header parsing, and was not storing the HTML content in the `resources` array for tests that check the content. 5ed0255 fixes that and with no other changes 494510c should pass now.

**Comment by april** [comment]
Sorry about this, but I misread your IRC message. Would you be willing to rebase this for me, please? Thanks!

**Comment by floatingatoll** [comment]
Yep, it’s already in my rerere cache, ETA 2 hours or so.

**Comment by floatingatoll** [comment]
#327 included these commits, so you're already set.

**Pull request closed without merging**
